let data = new Date()

console.log(data.getDay())
console.log(data.getDate())
console.log(data.getMonth())
console.log(data.getFullYear())
console.log(data.getHours())
console.log(data.getMinutes())
console.log(data.getSeconds())
console.log(data.getTime())
console.log(data.getUTCDate())
data = data.setFullYear(2024)
console.log(data)